# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (1)
# #########################################################################

class ScrumUpdate(BaseModel):
    date: typing.Optional[str] = None
    summary: typing.Optional[str] = None
    accomplishments: typing.Optional[str] = None
    plans: typing.Optional[str] = None
    sentiments: typing.Optional[str] = None
    blockers: typing.Optional[str] = None
    speakers: typing.List[str]
    duration_minutes: typing.Optional[int] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
